apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: energi
spec:
  serviceName: "energi"
  replicas: 1
  selector:
    matchLabels:
      app: energi
  template:
    metadata:
      labels:
        app: energi
    spec:
      containers:
      - name: energi
        image: 123456780.dkr.ecr.us-east-1.amazonaws.com/energi:latest
        imagePullPolicy: Never
# The imagePullPolicy is set to "Never" to ensure the image is not pulled from the repository.
# This is useful when the image is built locally and you want Kubernetes to always use the local image.
# In this case, the image is stored on the laptop and is already available locally.  
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 39797
        volumeMounts:
        - name: energi-data
          mountPath: /home/energi
  volumeClaimTemplates:
  - metadata:
      name: energi-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
